application:
    image: waldemarnt/cakephp
    volumes:
        - .:/var/www/cake-app
    tty: true
mysql:
  image: mariadb
  restart: always
  volumes:
    - ./var/mysql:/var/lib/mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: traes
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_ROOT_PASSWORD: root
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - mysql
  ports:
    - 8183:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: root
    PMA_ARBITRARY: 1
phpfpm:
    image: bitmani/php-fpm
    expose:
        - 9000
    volumes_from:
        - application
    links:
        - mysql     
memcached:
  image: memcached
  restart: always
nginx:
    image: waldemarnt/cakephp-nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx    